trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core'
  inputs:
    packageType: 'sdk'
    version: '5.0.103'

- script: dotnet test $(CAMINHO_PROJETO_TESTES) --verbosity minimal --logger:"html;LogFileName=resultado-testes.html" --collect:"XPlat Code Coverage"
  displayName: 'Run DotNet test'

- script: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.6
  displayName: 'Install Report Generator'
  condition: always()

- script: |
    cd Groffe.AspNetCore.Indisponibilidade.Testes/TestResults
    ls
    cd $(ls -d */|head -n 1)
    reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
  displayName: 'Run Report Generator'
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: 'Upload Artifact Test Result'
  inputs:
    PathtoPublish: 'Groffe.AspNetCore.Indisponibilidade.Testes/TestResults'
    ArtifactName: 'resultado-testes'
    publishLocation: 'Container'


