trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core'
  inputs:
    packageType: 'sdk'
    version: '5.0.103'

- task: DotNetCoreCLI@2
  displayName: 'Run DotNet test'
  inputs:
    command: 'test'
    projects: '$(CAMINHO_PROJETO_TESTES)'
    arguments: '--verbosity minimal --logger:"html;LogFileName=resultado-testes.html" --collect:"XPlat Code Coverage"'

- script: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.6
  displayName: 'Install ReportGenerator'
  condition: always()
  
- script: |
    cd $(CAMINHO_PROJETO_TESTES)/TestResults
    cd $(ls -d */|head -n 1)
    reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
  displayName: 'Run ReportGenerator'
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: 'Publish test results'
  inputs:
    PathtoPublish: '$(CAMINHO_PROJETO_TESTES)/TestResults/'
    ArtifactName: 'resultado-testes'
    publishLocation: 'Container'