trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core'
  inputs:
    packageType: 'sdk'
    version: '5.0.103'
- task: DotNetCoreCLI@2
  displayName: 'Run DotNet test'
  inputs:
    command: 'test'
    projects: '$(CAMINHO_PROJETO_TESTES)'

- script: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.6
  displayName: 'Install Report Generator'
  condition: always()

- script: |
    cd /home/vsts/work/_temp
    ls
    cd $(ls -d */|head -n 1)
    reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
  displayName: 'Run Report Generator'
  condition: always()


